### ISSUE TITLE
I met this error: line 63

### ISSUE THREAD

**Issue by bemoregt** [zubairr/image-clustering-phash#1]
Hi, @zubairr 

I met this error:
-------------------------------
kraken:image-clustering-phash dti$ python3 image_clustering.py 
  File "image_clustering.py", line 63
    return reduce(lambda x, (y, z): x | (z << y),
                            ^\
--------------------------------

what's wrong with me?

Thanks.

**Comment by ghost** [comment]
@bemoregt   change python version to 2   ,  python2
